### ISSUE TITLE
리액트 심화주차 개인과제 리뷰 - 김병연 튜터

### ISSUE THREAD

**Issue by ByungyeonKim** [G-NooN/advanced-fan-mail-box#1]
안녕하세요, 진훈님 벌써 심화주차 리뷰를 하게 되었네요. 바로 시작해 볼게요. :)

# 성공/실패에 대한 처리

https://github.com/G-NooN/advanced-fan-mail-box/blob/1d929e8bfe0f8d4fd5e5a1619fb53911bd4e29af/src/pages/Login.jsx#L28-L65

저는 진훈님이 작성하신 것처럼 사용하는 쪽에서 성공/에러에 대한 처리를 해주는 것을 좋아해요. 서버와의 통신에 대한 로직은 숨기고, 성공이나 실패 시 어떤 메시지를 띄울지는 최종 사용자에게 맡기는 거죠. 다만, 코드 가독성을 위해 회원가입과 로그인에 대한 로직을 함수로 따로 빼는 건 어떨까요?

# 곳곳에 있는 개발 흔적들

https://github.com/G-NooN/advanced-fan-mail-box/blob/1d929e8bfe0f8d4fd5e5a1619fb53911bd4e29af/src/shared/redux/modules/mailListSlice.js#L11-L16

깃헙 저장소에 최종으로 제출 시, console.log()가 있는지 꼭 확인하고 제출하시는 것을 추천드릴게요.(꼭 필요한 게 아닌 개발하면서 확인을 위해 사용한 console.log()) 나중에 기술 과제를 볼 때 감점 사유가 될 수 있어요.

# mailList

https://github.com/G-NooN/advanced-fan-mail-box/blob/1d929e8bfe0f8d4fd5e5a1619fb53911bd4e29af/src/pages/Detail.jsx#L8-L10

`mailList`는 객체이기 때문에 배열 메서드인 `find` 사용 시 에러가 납니다! `mailList`의 `letters`를 의도하신 걸까요?

# named export 

https://github.com/G-NooN/advanced-fan-mail-box/blob/1d929e8bfe0f8d4fd5e5a1619fb53911bd4e29af/src/api/axiosAPI.js#L3-L17

https://github.com/G-NooN/advanced-fan-mail-box/blob/1d929e8bfe0f8d4fd5e5a1619fb53911bd4e29af/src/pages/Login.jsx#L1

axiosAPI를 named export 하셨는데, 불러오는 쪽에서는 그렇지 못한 것 같아요. 저 같은 경우에는 바로 에러가 떴는데 혹시 이상 없으셨을까요?

---

이렇게 피드백을 드려봤습니다. 저번 리뷰 때 디렉토리 구조에 대해서 얘기를 나눈 적이 있었죠. 고민의 흔적이 보이네요. 🧐 이번 아웃소싱 프로젝트도 화이팅입니다! 고생하셨습니다. 👏

**Comment by G-NooN** [comment]
감사합니다. 미완성 상태로 제출했어서 부족한 부분이 많았습니다. 피드백 참고해서 발전시키도록 하겠습니다.
